// This file was generated by PermissionsDispatcher. Do not modify!
package com.zf.lottery.view;

import android.support.v4.app.ActivityCompat;

import permissions.dispatcher.PermissionUtils;

class PermissionsDispatcher {
    private static final int REQUEST_EXTERNAL_STORAGE = 0;
    private static final String[] PERMISSION_EXTERNAL_STORAGE = new String[]{"android.permission.READ_EXTERNAL_STORAGE"};

    private PermissionsDispatcher() {
    }

    public static void requestDataWithCheck(SscActivity target) {
        if (PermissionUtils.hasSelfPermissions(target, PERMISSION_EXTERNAL_STORAGE)) {
            target.requestData();
        } else {
            if (PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_EXTERNAL_STORAGE)) {

            } else {
                ActivityCompat.requestPermissions(target, PERMISSION_EXTERNAL_STORAGE, REQUEST_EXTERNAL_STORAGE);
            }
        }
    }

    static void onRequestPermissionsResult(SscActivity target, int requestCode, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_EXTERNAL_STORAGE:
                if (PermissionUtils.getTargetSdkVersion(target) < 23 && !PermissionUtils.hasSelfPermissions(target,
                        PERMISSION_EXTERNAL_STORAGE)) {

                    return;
                }
                if (PermissionUtils.verifyPermissions(grantResults)) {
                    target.requestData();
                } else {
                    if (!PermissionUtils.shouldShowRequestPermissionRationale(target, PERMISSION_EXTERNAL_STORAGE)) {
                    } else {
                    }
                }
                break;
            default:
                break;
        }
    }
}
